In [3]:
import numpy as np
X=np.array([[0,0,1,1],[1,0,0,0],[0,1,1,0],[0,0,0,1]])
W_=np.array([[0.2,0.9],[0.4,0.7],[0.6,0.5],[0.8,0.3]])
lr=0.5
epoch=2
for iter in range(epoch):
    for i in range(X.shape[0]):
        temp=[]
        print("for input",X[i,:])
        for j in range(W_.shape[1]):
            sum=0
            for k in range(W_.shape[0]):
                
                sum=sum+((X[i][k]-W_[k][j])**2)
            temp.append(sum)
        if(temp[0]<temp[1]):
            index=0
        else:
            index=1
        print("neuron at position",index,"won")
        for p in range(W_.shape[0]):
            W_[p][index]=W_[p][index]+lr*(X[i][p]-W_[p][index])
        print(W_)
    lr=lr*0.5

for input [0 0 1 1]
neuron at position 0 won
[[0.1 0.9]
 [0.2 0.7]
 [0.8 0.5]
 [0.9 0.3]]
for input [1 0 0 0]
neuron at position 1 won
[[0.1  0.95]
 [0.2  0.35]
 [0.8  0.25]
 [0.9  0.15]]
for input [0 1 1 0]
neuron at position 0 won
[[0.05 0.95]
 [0.6  0.35]
 [0.9  0.25]
 [0.45 0.15]]
for input [0 0 0 1]
neuron at position 0 won
[[0.025 0.95 ]
 [0.3   0.35 ]
 [0.45  0.25 ]
 [0.725 0.15 ]]
for input [0 0 1 1]
neuron at position 0 won
[[0.01875 0.95   ]
 [0.225   0.35   ]
 [0.5875  0.25   ]
 [0.79375 0.15   ]]
for input [1 0 0 0]
neuron at position 1 won
[[0.01875 0.9625 ]
 [0.225   0.2625 ]
 [0.5875  0.1875 ]
 [0.79375 0.1125 ]]
for input [0 1 1 0]
neuron at position 0 won
[[0.0140625 0.9625   ]
 [0.41875   0.2625   ]
 [0.690625  0.1875   ]
 [0.5953125 0.1125   ]]
for input [0 0 0 1]
neuron at position 0 won
[[0.01054688 0.9625    ]
 [0.3140625  0.2625    ]
 [0.51796875 0.1875    ]
 [0.69648438 0.1125    ]]
